### ISSUE TITLE
Unknown packet type 1 just parsed a voiceInit

### ISSUE THREAD

**Issue by triested** [demostf/demos.tf#1]
When I try to view some demos, the loading wheel appears for a while, and then the error screen comes up with the message "Unknown packet type 1 just parsed a voiceInit." I've tried opening them on firefox and chrome on win10, and the same issues occur.

I think it's only happening with demos I attempt to open from my own profile, as opposed to the main page, but I could be wrong.

**Comment by mkrl** [comment]
Doubling that, bumped into a few errors with my demos, some of them work though. The packet type happened to have different type from time to time.
Ex.: https://demos.tf/viewer/46582 (opening for the first time most likely runs processing and then error, opening it for the next time gets us the error immediately)
https://demos.tf/viewer/38130 "packet type 58" here.

**Comment by icewind1991** [comment]
This one should be fixed, feel free to reopen if you run into the same problem again
