### ISSUE TITLE
Keep getting json_decode error: Syntax error

### ISSUE THREAD

**Issue by TomatDividedBy0** [demostf/demos.tf#13]
Here's the demo I tried to upload.

[demo.zip](https://github.com/demostf/demos.tf/files/3518404/demo.zip)

Here's the result:
![image](https://user-images.githubusercontent.com/25469801/63312974-fae7eb80-c2d0-11e9-9e6e-58bc9aa2fb73.png)

**Comment by icewind1991** [comment]
Thanks for providing the demo file.

Fixed the parsing issue and it now works without problems: https://demos.tf/298801
