### ISSUE TITLE
Error 404 upon downloading slightly older and recent demos

### ISSUE THREAD

**Issue by ultiduoarrow** [demostf/demos.tf#34]
Hello. Recently, I tried to download some older STVs from some of my previous teams and found that I can't seem to download them. Upon clicking download, I'm redirected to a "Error 404" page. The demos are from 2020, which does make them old but they aren't ancient history quite yet. I tried to download an STV from 5 days ago to test if it worked, but also got a 404 page.  I will post links to the demos I tried to download and attach an image of the 404 page. Thank you for reading and thank you for demos.tf, it's a great service. My friend had the same issue when trying to download these demos.

https://demos.tf/483751 (from 2020)
https://demos.tf/454023 (from 2020)
(https://demos.tf/770603 (random demo from 5 days ago from posting this)
https://demos.tf/773068 (demo from 18 hrs ago from posting this, download works)

404 page I get when trying to download these demos:
![404](https://user-images.githubusercontent.com/98705598/151710177-e218e006-3a48-4eff-bc74-9c8fc9e942b1.PNG)

**Comment by icewind1991** [comment]
fixed
