### ISSUE TITLE
Editor not processing demo

### ISSUE THREAD

**Issue by Thespikedballofdoom** [demostf/demos.tf#47]
Gives a zero to zero cut range on upload that cannot be changed. Does it always have to cut the demo? I wish there was a toggle to not cut it
https://drive.google.com/file/d/1ViJtyZmWGARyh1Wjw87w3bpTtRAa1AYe/view?usp=sharing

**Comment by icewind1991** [comment]
this was caused by the demo being truncated (generally caused by tf2 shutting down uncleanly) meaning that the demo doesn't have a length set in the header.

Added a fallback to counting the ticks in the demo when opening
