### ISSUE TITLE
Icons slightly too high 

### ISSUE THREAD

**Issue by Shpee64** [demostf/demos.tf#5]
(First I just wanna mention that this is one of the best things ever made for tf2 imo. So me reporting even minor issues is not to discourage you but just to give you as much feedback as possible.)
I just watched a granary demo and the icons that represent players appear to be a bit higher on the online demo than actually in-game. I don't know if this is only on granary or also on other maps.
Thanks for making this! :D

**Comment by icewind1991** [comment]
Alignment of player icons to the map image should be better now
