### ISSUE TITLE
Gullywash map image is upside down

### ISSUE THREAD

**Issue by minicircle** [demostf/demos.tf#7]
First of all, phenomenal work @icewind1991. Thanks for making such a useful browser-based demo playback tool.

When reviewing a match, one of my teammates noticed that the Gullywash map image is upside down; RED team appears to spawn on BLU's side, and vice versa. This can be seen in the attached image. (The font issue also shown in the picture happens to me on Chrome and Firefox on Windows 10; I've submitted a pull request to fix this).

![gullywash](https://cloud.githubusercontent.com/assets/23437981/24077858/382a751e-0c29-11e7-9b6e-4af718df3d2d.PNG)

**Comment by icewind1991** [comment]
(all (almost) symmetrical maps are currently upside down, but don't tell anyone that 🙈 )

**Comment by icewind1991** [comment]
Rendering of player icons have been mirrored to match the map images
